### ISSUE TITLE
reuse-tab导致浏览器挂起

### ISSUE THREAD

**Issue by zjsun** [ng-alain/delon#121]
- ng-alain version: 1.1.3
- Angular version: 6.0.9

## 【必填项】重现链接，Reproduction link
![reuse-tab-browser-hang](https://user-images.githubusercontent.com/5276207/42671990-c7edf1fc-8695-11e8-9508-255a30c4c31f.jpg)

## 重现步骤，Steps to reproduce

1.  打开2个（含）以上tab；
2. 刷新浏览器，加载完毕后，此时只留下刷新浏览器时那个tab；
3. 点菜单，使出现多个tab；
4. 直接去关闭2）中的那个tab；
5. 浏览器开挂。。。。。

**Comment by cipchk** [comment]
麻烦提供一个在线可重现示例。

**Comment by cipchk** [comment]
关掉issues，若有进一步细节请提供相应的重现示例。
