### ISSUE TITLE
timeline折线图 能否开放设置x坐标开始和结束位置

### ISSUE THREAD

**Issue by 80631004** [ng-alain/delon#122]
现在只显示8天数据，如果需要显示一个月数据，展示出来的效果如下图所示，非常怪异，是否可以随我传入的数据来展示所有趋势坐标

原图：
![org](https://user-images.githubusercontent.com/30076492/42792353-66d59ea0-89a7-11e8-9146-40b15260efdb.png)

期望展示下图所示：
![expert](https://user-images.githubusercontent.com/30076492/42792356-6880482c-89a7-11e8-8013-a8b95cad11ae.png)

**Comment by cipchk** [comment]
暂时以 pro.ant.design 的序列组件功能为基准，不考虑进一步扩展。
