### ISSUE TITLE
JWTInterceptor should have a whitelist (or blacklist) URLs in configuration

### ISSUE THREAD

**Issue by uded** [ng-alain/delon#126]
In a regular scenario, in a mature API, a request to an auth REST API URL should not require a token. Currently, if you use JWTInterceptor, it will try to attach JWT token to all requests and check if the token consists of 3 parts. This is not correct since for the authentication requests the token is not there yet. Look at [angular2-jwt](https://github.com/auth0/angular2-jwt) project by Auth0. As this is missing I actually prefer that lib right now, but then to use it I need further modifications in Delon/ng-alain code...

**Comment by uded** [comment]
This makes no practical sense to introduce some key just because I want to ignore a full set of URLs used for authentication or any other operation. Additionally, I will need to send it, it will go to logs, etc.

I actually believe that this behavior is similar or the same in SimpleInterceptor, but I haven't tested it yet fully. Except, obviously, it will not complain about JWT token not conforming to the standard but rather it will make my request ignored/going nowhere.

**Comment by cipchk** [comment]
Close the delon issue and we will track bugs or features in the [ng-alain](https://github.com/ng-alain/ng-alain/issues) repository.
