### ISSUE TITLE
建议不要用ad这个prefix，好像浏览器装了adBlock会把这个拦截

### ISSUE THREAD

**Issue by tonny008** [ng-alain/delon#131]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by pbbisme** [comment]
浏览器的广告拦截插件是这样的， 会默认把ad 开头的当广告屏蔽掉，以前写过个以ad开头的样式，运行在装了广告拦截器的浏览器里面，样式都不生效了
