### ISSUE TITLE
SimpleTable events should include all information for backend calls in the event

### ISSUE THREAD

**Issue by uded** [ng-alain/delon#134]
As far as for creating separate events for each type of operation (`change`, `sort`, `filter`) I do not really have an opinion (although, honestly, one would do...), in either case for each of them this component should include all related information so the method handling such a change can include them all in processing. Therefore something like:
```
interface SimpleTableStateInterface {
    pi?: number;
    ps?: number;
    sort?: {
        by: string | Comparator<any>
        direction: boolean;
    }[];
    filters?: ({property: string, value: string} | Filter<any>)[];
}
```
Where `Filter` and `Comparator` might be introduced as a function as well. 

This interface can provide a full _state_ for the component and, hence, greatly simplify state events handling for a back-end call. 

Further extensions can be made by providing implementations of given interfaces.

I do understand that state handling can be introduced in client code, but since the component itself have to handle that already I do not believe decoupling that makes any sense.

**Comment by cipchk** [comment]
Yes. a good suggestion and i working hard to improve these details, releaed issues:

-https://github.com/cipchk/ng-alain/issues/588

**Comment by uded** [comment]
I am happy to help - I already started to look into how to refactor SimpleTable to make it more backend-friendly...

**Comment by cipchk** [comment]
Thank you!

ng-alain need more help. 🥇
