### ISSUE TITLE
sidebar-nav should use Ant Design menu

### ISSUE THREAD

**Issue by uded** [ng-alain/delon#138]
I can't find a reasonable answer why `sidebar-nav` doesn't use Ant Design menu component. Taking into consideration that it would limit additional code and reliance on custom implementation it would be advisable to migrate to that common one in favor of custom code.

**Comment by cipchk** [comment]
the `nz-menu` has many features that can't be implemented, like: heading layout, badge, external link etc...

i was looking forward to `nz-menu` being more mature in the future.

**Comment by cipchk** [comment]
in face, ng-alain includes [ant design pro](https://e.ng-alain.com/theme/antd-pro) theme, you can register a account and tell me email address, i will send to you.

**Comment by uded** [comment]
I understand that `nz-menu` might be missing some features, but honestly - can't find any that are missing there or would be difficult to implement as an extension. It would be beneficial to rather extend `nz-menu` and submit PR than split aside and duplicate features. Please, be more specific what is missing and where so maybe there is a path to achieve a better implementation that will be closer to common a component.

Also, the sidebar is hardcoded into ng-alain, and I am missing the point of that as well...

Regarding ant design pro - can you give some context somewhere in English? It's all in Chinese, hard to understand a point of that...

**Comment by cipchk** [comment]
The special layout required (head name first) by ng-alain is difficult to get supported in `nz-menu`, because it always has the same priority as ant design.

ng-alain has only one theme (just [default](https://cipchk.github.io/ng-alain/) theme) for publicity, and [ant design pro by ng-alain](https://e.ng-alain.com/theme/antd-pro) as another ng-alain for theme thanks to all contributor users, currently not open to all users.

Anyway, you need to provide an email address of a registered to get it.

**Comment by uded** [comment]
OK, I am not sure - regarding the nav bar - what you exactly mean. The static sections in NG-Alain I see are different in `nz-menu` in a way that they are main collapsible menu elements. It's a slight change of logic, but insignificant from the implementation perspective. UX is different in the way that the main groups are collapsible, which to a certain extent make sense.

![zrzut ekranu 2018-08-19 o 20 04 27](https://user-images.githubusercontent.com/218623/44311160-20ef5d00-a3eb-11e8-8c48-122885517102.jpg)

It makes even more sense if you take a look pop-up behavior for a multi-level menu like this:

![zrzut ekranu 2018-08-19 o 20 05 10](https://user-images.githubusercontent.com/218623/44311168-42504900-a3eb-11e8-8297-3b9ee41f49de.jpg)

The thing that I see missing is the badges, but those should be relatively easy to implement as an extension since the content of each element is pure HTML.

Do you have some design documentation so I can understand the logic, idea and what is behind this component in the current state?

**Comment by cipchk** [comment]
Close the delon issue and we will track bugs or features in the [ng-alain](https://github.com/ng-alain/ng-alain/issues) repository.
