### ISSUE TITLE
关于simple-table的排序

### ISSUE THREAD

**Issue by funfi** [ng-alain/delon#141]
基于后端分页的情况下
如果是data赋值（后端已经排序好），是否可以考虑不需要前端排序
两处地方会触发前端排序（data赋值时和sortchange的事件）

**Comment by jackzhum** [comment]
你这个前端排序设置成与后台排序一致不就好了，不然既然用了后台排序干脆关掉前端排序。

**Comment by funfi** [comment]
同个字段的排序，前端重排之后不一致（应该是对中英文数字这种排序方式算法不一致导致的）

**Comment by cipchk** [comment]
关掉issues，若有进一步细节请提供相应的重现示例。
