### ISSUE TITLE
g2-bar的data切换问题

### ISSUE THREAD

**Issue by zlhy** [ng-alain/delon#144]
各位好：
      我在切换g2-bar的data时，当data的length从1切换到7 时，data数据更改了，但是图没有变，这个要特殊处理吗？

**Comment by cipchk** [comment]
麻烦提供一个可重现示例。

**Comment by zlhy** [comment]
@cipchk 
https://github.com/zlhy/ng-alain/blob/master/src/app/routes/dashboard/analysis/analysis.component.ts
ng-alain的分析页

**Comment by zlhy** [comment]
@cipchk 调试了一下，发现修改data后，G2BarComponent的resize方法 没有调用到 runInstall方法。

**Comment by zlhy** [comment]
@cipchk 还有个问题： 
<nz-card [nzLoading]="loading">
  <g2-bar height="295" [title]="'访问量趋势'" [data]="data"></g2-bar>
</nz-card>
这种情况下，第一次加载时，g2-bar没有显示label，如果去掉 [nzLoading]="loading" 可以显示 label。

**Comment by zlhy** [comment]
g2-bar在 nz-card 内
