### ISSUE TITLE
SimpleTable should be able to hide columns based on screen sizes

### ISSUE THREAD

**Issue by uded** [ng-alain/delon#145]
It would be a great and reasonably simple extension to do - hide columns based on screen size, similar to CSS classes that can do so. It can partially remedy #139...

**Comment by cipchk** [comment]
You can try using `className` property in `columns`, ng-alain theme styem has some corresponding [responsive](https://next.ng-alain.com/theme/tool#Responsive) styles.

**Comment by uded** [comment]
Yes, I have tried with not satisfactory result.

IMHO, regarding this and #139 - table should be really redesigned...

**Comment by cipchk** [comment]
I have refactored some of the details and optimize the following sections before the rc version:

- performance
- developing nature

Https://next.ng-alain.com/components/table

if possible the responsive question should also be part of the column description.

**Comment by cipchk** [comment]
Hi @uded 

I tried to work a [responsive effect](https://next.ng-alain.com/components/table/zh#components-table-responsive)

**Comment by uded** [comment]
Looks interesting!

My suggestion, which I was trying to explore, would be to add a parameter to each column and hide columns based on the sizes. Quite often you just do not need certain columns on a smaller screen or, rather, you can sacrifice them for readability. If you have one or two columns which you can get rid of in case of a small screen factor that might be a pretty nice option to optimize this component.

Furthermore, there is, IMHO, a problem that should be fairly easy to mitigate - namely the size of the table. Currently, there are three _sizes_ available - large, medium and small. The difference in a mobile view is huge between them:

![zrzut ekranu 2018-09-01 o 18 39 51](https://user-images.githubusercontent.com/218623/44947539-f6ec6080-ae16-11e8-87b5-98b5a3d68edf.jpg)

vs the same table just in small size:

![zrzut ekranu 2018-09-01 o 18 42 49](https://user-images.githubusercontent.com/218623/44947540-ff449b80-ae16-11e8-8ac7-f8e321f69da9.jpg)

But this is a more general problem with Ant I believe as none of their components will react to size changes like I would expect them. And, on top of that, I believe further tweaking of the stylesheet should be possible...
