### ISSUE TITLE
_HttpClient中的loading如何使用？

### ISSUE THREAD

**Issue by shaohongzhu** [ng-alain/delon#188]

**Comment by cipchk** [comment]
`loading` 是一个 `public` 属性，在你注入 `_HttpClient` 时可以直接访问

**Comment by shaohongzhu** [comment]
> `loading` 是一个 `public` 属性，在你注入 `_HttpClient` 时可以直接访问
多谢，知道怎么用了，确实很方便，省了不少loading的设置
