### ISSUE TITLE
是否可以考虑一下在simpleTable加入拖动列的功能

### ISSUE THREAD

**Issue by gassyou** [ng-alain/delon#204]
Hello  卡色

不知道，作者有没有意向在simple-table里面加入拖放列的功能？

我尝试了一下使用“NGX-DND”和ng-zorro的table控件结合，可以简单地实现拖放列的功能。
![gif](https://user-images.githubusercontent.com/2518449/46709222-3ce9df00-cc75-11e8-9c1a-2f19f308dad2.gif)

我想将这个table简单封装一下，所以在学习simple-table的代码，看看里面是如何封装的，
然后，碰到了疑惑是，发现在simple-table里面使用了“OnPush”的策略，

那么，在我的认识里面，要使“simple-table”进行脏值检测，
要么,@Input的值发生了变更（引用的变更）
要么，在“simple-table”使用了“MarkForCheck()"
要么，手动了进行检测

但是，我在代码里面并没有发现有以上的处理，
而且在传入input的时候，也没有说一定要传入，不可变的数据之类。

不知道，你是怎么让simple-table触发脏值检测的？

Best regards

**Comment by cipchk** [comment]
https://github.com/ng-alain/delon/blob/master/packages/abc/table/table.component.ts#L540

**Comment by gassyou** [comment]
@cipchk 

哦。了解。了解。 看漏了，不好意思。
