### ISSUE TITLE
ModalHelper should either close all modals on route change (i.e. back button) or give object to handle that

### ISSUE THREAD

**Issue by uded** [ng-alain/delon#210]
- ng-alain version: 1.4.5
- Angular version: 6.1.x

Currently, when calling a `ModalHelper` I do not see modal created being destroyed on changing the route/page, but rather it persists on top of the app. Neither do I see a quick way to assign modal created to a property using '.create' or '.createStatic' to handle that with 'ngOnDestroy()'.

My suggestion would be to destroy the modal on route change automatically.

**Comment by cipchk** [comment]
https://github.com/ng-alain/ng-alain/blob/master/src/app/app.component.ts#L37
