### ISSUE TITLE
通过cli创建的项目，侧边栏是可以收起的，但是通过clone的项目就不能展开收起

### ISSUE THREAD

**Issue by hey9162** [ng-alain/delon#215]
- ng-alain version: 2.0.0-beta.4
- Angular version: 6.1.10

## 【必填项】重现链接，https://ng-alain.github.io/ng-alain/#/dashboard/v1

- 截图：
![tim 20181015093634](https://user-images.githubusercontent.com/22787406/46925325-e22dfa00-d05d-11e8-8223-b2f6299d8724.png)
![tim 20181015093743](https://user-images.githubusercontent.com/22787406/46925350-025db900-d05e-11e8-8f6f-62ba4a749b1c.png)

**Comment by cipchk** [comment]
https://github.com/ng-alain/delon/pull/201
fix in `v2.0.0-beta.5`
