### ISSUE TITLE
Gitter chat? Something that can be easily reached...

### ISSUE THREAD

**Issue by uded** [ng-alain/delon#221]
As I have a couple of questions, requests or just doubts I would like to reach out to discuss simple things, coordinate some changes and development, etc. Would be nice to be able to reach someone, a community, but there is none I can reach. Tried QQ, but no luck. 

Can we use Gitter? It's tightly connected with Github, making it easy to use. 

Or something else. That works in Europe as well. Please.

**Comment by cipchk** [comment]
@uded  [![Gitter](https://img.shields.io/gitter/room/cipchk/ng-alain.svg?style=flat-square)](https://gitter.im/cipchk/ng-alain)
