### ISSUE TITLE
select 的openChange onSearch事件定义在UI里面失效

### ISSUE THREAD

**Issue by navisoftware** [ng-alain/delon#252]
- ng-alain version: ^2.0.0-beta.0
- Angular version: ^6.1.0

## 【必填项】重现链接，Reproduction link

代码: delon/packages/form/src/schema/ui.ts
这个UI里面根本就没有关于openChange onSearch的事件定义,
导致最后select 组件 即便是在UI里面定义了这些事件.执行的时候组件里面也找不到这个定义导致定义的事件都没有执行.

**Comment by cipchk** [comment]
不明白你在说什么，麻烦提供相应的重现示例。

**Comment by navisoftware** [comment]
$select: {
                widget: 'select',
                onSearch: (text: string) => {
                     //在select里面输入文字 在这里是不执行的.
                }
}

**Comment by navisoftware** [comment]
好吧,最新版是可以的.我升级一下试试.
