### ISSUE TITLE
select组件的element通过asyncData获取的options在经过visibleIf隐藏后再显示，会丢失options

### ISSUE THREAD

**Issue by zd5043039119** [ng-alain/delon#257]
- ng-alain version: 1.5.1
- Angular version: 6.1.6

## 【必填项】重现链接，Reproduction link
https://ng-alain-setup-zyqm6r.stackblitz.io

## 重现步骤，Steps to reproduce
点击Button A，可见A-ID下有选项A,B
点击Button B，A-ID隐藏
再点击Button A, A-ID下没有选项

- A-ID用asyncData方式配置选项会丢失
- B-ID用enum方式配置选项不受影响

**Comment by cipchk** [comment]
目前无法清楚为什么会引起数据源会被自动设置为 `undefined`，但的确已经触发了 `asyncData`，估计这个 bug 只能搁置。

但有两种替代方案：

- 使用 `enum` 替代 `asyncData`， 并重新刷新  Schema
- 使用 `onSearch` 实时搜索模式替代 `asyncData`

**Comment by zd5043039119** [comment]
@cipchk 之前visibleIf这种场景通过你给的临时替代方案暂时处理了,但是目前存在一个场景无法解决,就是Array的组件中存在级联的查询.只能存在asyncData,而一旦Array中任意一个元素被删除后asyncData也无法生效.所以我调试了下发现问题在于
```javascript

export function getData(
  schema: SFSchema,
  ui: SFUISchemaItem,
  formData: any,
  asyncArgs?: any,
): Observable<SFSchemaEnum[]> {
  if (typeof ui.asyncData === 'function') {
    return ui
      .asyncData(asyncArgs)
      .pipe(
        takeWhile(() => ui.__destroy !== true),
        map(list => getEnum(list, formData, schema.readOnly)),
      );
  }
  return of(getCopyEnum(schema.enum, formData, schema.readOnly));
}
```
takeWhile中的predicate如果返回的是false,则可以在管道中继续执行next,但是所有visibleif或者Array中删除的操作都会触发SFItemComponent的
```javascript
  ngOnDestroy(): void {
    this.formProperty.ui.__destroy = true;
    this.ref.destroy();
  }
```
导致该FormProperty的ui对象的'__destroy'属性为true,所以
```javascript
takeWhile(() => ui.__destroy !== true)  // executed
map(list => getEnum(list, formData, schema.readOnly)) //will blocked
```
是无法执行下去的.这就是为什么asyncData触发了但是没有更新ui的原因
```javascript
 getData(this.schema, this.ui, this.formProperty.formData).subscribe(
      list => {
        this.data = list;
        this.hasGroup = list.filter(w => w.group === true).length > 0;
        this.detectChanges();
      },
    );
```
管道的最后一个subscribe没有执行,  this.detectChanges();也不会触发

我在debug模式中在SFItemComponent中ngOnInit去除this.formProperty.ui.__destroy属性可解决问题
```javascript
 ngOnInit(): void {
    if(this.formProperty && this.formProperty.ui) { 
        delete this.formProperty.ui.__destroy;
    }
    this.terminator.onDestroy.subscribe(() => {
    　this.ngOnDestroy();
    });
  }
```
但不知会否有其他不良影响.
