### ISSUE TITLE
locale.tr

### ISSUE THREAD

**Issue by etuncay** [ng-alain/delon#288]
[tr_TR.ts.zip](https://github.com/ng-alain/delon/files/2603236/tr_TR.ts.zip)

thanks.

**Comment by cipchk** [comment]
Thank you very much, do you can provide language for ng-alain?

https://github.com/ng-alain/ng-alain/blob/master/src/assets/tmp/i18n/en-US.json

**Comment by etuncay** [comment]
> Thank you very much, do you can provide language for ng-alain?
> 
> https://github.com/ng-alain/ng-alain/blob/master/src/assets/tmp/i18n/en-US.json

[tr-TR.json.zip](https://github.com/ng-alain/delon/files/2607252/tr-TR.json.zip)

**Comment by cipchk** [comment]
hi @etuncay 
this is "🇹🇷" tr-TR locle flag?
