### ISSUE TITLE
SF中必需属性定义优化建议

### ISSUE THREAD

**Issue by fengzhi09** [ng-alain/delon#300]
sf组件中支持必须属性有两种方式使用required:string[] 或者条件类（if,then,else）支持
我建议required的定义方式变为
```
interface RequiredItem{
     if:{
          properties?: { [key: string]: SFSchema;};
          items?:SFSchema;
     };
     then:{required?:string[]};
}
interface SFSchema{
    ……
    required?:string[];
    cases?:RequiredItem[];
}
```
因为单层if/else实现定义如下的登陆界面将会较为困难：

```
interface user{
    type:enum;  //登陆方式，必填（游客，手机密码，账号密码，邮箱密码）四个中一个
    email:string;  //邮箱，登录方式为”邮箱密码“时必填
    mobile:string;  //手机号，登录方式为”手机密码“时必填
    account:string;  //账号，登录方式为”账号密码“时必填
    password:string;  //密码，登录方式为”游客“时选填，其余必填
}
```

使用新定义的就很简单了
```
schema:{
    ……
    cases:[
        {
           if:{properties:{type:{enum:["游客"]}}},
           then:{required:[”account“]
        },
        {
           if:{properties:{type:{enum:["手机密码"]}}},
           then:{required:[”mobile“,"password"]
        },
        {
           if:{properties:{type:{enum:["邮箱密码"]}}},
           then:{required:[”email“,"password"]
        },
        {
           if:{properties:{type:{enum:["账号密码"]}}},
           then:{required:[”account“,"password"]
        },
    ]
}
```
同理还可以实现更为复杂表单的可视化管理，比如一张表单上要求：
字段A、B、C必填，字段D选填;
字段E、F当字段A值为a1时必填，其余不可见;
字段H当字段A值为a2时必填，其余选填但可见;
字段G当字段A值为a3时必填;
使用cases模式很容易实现，但使用sf组件现在完全没办法做。

**Comment by cipchk** [comment]
必填项只有一种方式 [required](https://json-schema.org/latest/json-schema-validation.html#rfc.section.6.5.3) 这是 JSON Schema 的标准。

**Comment by cipchk** [comment]
我很同意你的观点，事实上 JSON Schema 也有条件表示式规范，只是 `sf` 并未实现这一部分，而目前的 `if` 是一个折中办法，但是依目前的实现方法若依你的方法来实现，实现成分并不复杂，但是可能会带来被滥用 `sf` 情况，基于目前 `if` 的实现方法会是乘积来校验，当目前元素含有一些长时间操作（例如：HTTP），会倒置一次交互产生N次的请求，虽然目标用户可以利用缓存解决，但是反而会增加使用成本。

`sf` 的设计目标本来就不是服务于所有表单，只是尽肯能简化部分表单，对于复杂交互，都不应该优先使用它。

不过，我会在未来对 `sf` 进一步增强与优化，保持 JSON Schema 完整标准的实现。

**Comment by cipchk** [comment]
Close the delon issue and we will track bugs or features in the [ng-alain](https://github.com/ng-alain/ng-alain/issues) repository.
