### ISSUE TITLE
Session lost in new tab

### ISSUE THREAD

**Issue by kherP** [ng-alain/delon#306]
- ng-alain version: 1.3.2
- Angular version: 6.1.0

## Issue

**first tab:**
![image](https://user-images.githubusercontent.com/12553063/49423255-c7f8d880-f7d1-11e8-9cea-2f4bfd978d98.png)

**second tab:**
![image](https://user-images.githubusercontent.com/12553063/49423341-245bf800-f7d2-11e8-8cbe-50f75f9375fe.png)

**code:**
![image](https://user-images.githubusercontent.com/12553063/49423383-4bb2c500-f7d2-11e8-8ccb-17e3f1af0c8f.png)

## 重现步骤，Steps to reproduce
After logged in and clicked to open a new tab, session lost. Session should be retained instead.

**Comment by cipchk** [comment]
Using `sessionStorage` for this is not possible, From the [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API#Web_Storage_concepts_and_usage) Docs.
