### ISSUE TITLE
打包到线上服务器，如何在用户不刷新的情况下 更新所用内容？

### ISSUE THREAD

**Issue by BecksWang** [ng-alain/delon#314]
做了更改发布到线上，但用户那边需要刷新才会加载到新的东西，查看了下发现index.html还是旧版的,请问如何在不刷新的情况下更新index.html？

**Comment by cipchk** [comment]
Service 设置不要缓存 `index.html`，自行百度。

**Comment by BecksWang** [comment]
那请问除了在页面加入meta标签 还有什么更好的办法吗
