### ISSUE TITLE
操作其他组件时，st会不断引起组件渲染

### ISSUE THREAD

**Issue by xuhailin** [ng-alain/delon#351]
- ng-alain version: 2.0.0
- Angular version: 6.1.0

不便提供重现链接

* 直接使用nz-zorro组件没有这种情况
* 使用onpush策略也没有用
![image](https://user-images.githubusercontent.com/20624418/50510681-9d92f600-0ac5-11e9-9cbf-31191a9e5e35.png)

```
//html
{{test()}}
<st
  [columns]="columns"
  [loading]="loading"
  [data]="data"
  [page]="{show: false}"
  (change)="tableChange($event)"
>
  <ng-template st-row="type" let-item>
      <span nz-tooltip [nzTitle]="item.type">
            <div class="type-text">
                {{item.type}}
             </div>
        </span>      
  </ng-template>
</st>
// component
test(): void {
   console.log(1234);
}
```

**Comment by xuhailin** [comment]
你好，虽然问题被关闭了，但我还是充满疑问啊，这点是没有办法改变的吗？

卡色 <notifications@github.com> 于2018年12月28日周五 下午5:38写道：

**Comment by cipchk** [comment]
@xuhailin 脱离环境我没有能力帮到你什么。

**Comment by xuhailin** [comment]
嗯，没关系，还是谢谢你的回复😀

卡色 <notifications@github.com> 于2018年12月28日周五 下午5:51写道：

**Comment by evilbinary** [comment]
@xuhailin 貌似是ng-zorro-antd版本问题，你选低版本就有这种bug。

**Comment by xuhailin** [comment]
@evilbinary  我用的angular6， 对应版本ng-zorro-ant是1.8.0，你用的版本多少没问题呢？

**Comment by evilbinary** [comment]
@xuhailin  最新的没有问题，1.7.x-1.8.x 有问题，我测试过的。

**Comment by xuhailin** [comment]
@evilbinary 我当时比较急，没有再使用st标签了，ng-zorro-ant最新的不是7.1.0了吗？你用的angular7吗？

**Comment by evilbinary** [comment]
@xuhailin 然而并没有

**Comment by xuhailin** [comment]
@evilbinary  嗯，谢谢你的热情回答，后面有时间我也升级看看

**Comment by evilbinary** [comment]
@xuhailin  哈哈，不用
