### ISSUE TITLE
FormProperty功能建议(必填和是否只读)

### ISSUE THREAD

**Issue by danxiaogui** [ng-alain/delon#352]
你好，在SF动态表单中，对表单中的一个字段动态进行必填设置、是否只读设置，通常需要对当前的schema的require和readOnly进行赋值，然后刷新整个schema和formData，这样的代价非常大且没有必要。

![image](https://user-images.githubusercontent.com/22045563/50521779-49f2cd80-0b02-11e9-924d-ebfd1d8ef912.png)
我在delon的源码中找到了[FormProperty](https://github.com/ng-alain/delon/blob/master/packages/form/src/model/form.property.ts)类，其中有个方法 setVisible（上图），可以设置动态表单中的字段是否可见，我想是否也能在FormProperty中扩展对必填和只读的操作，这样就不必在初始化动态表单完毕后，为了修改一个字段的必填、只读而去刷新整个Schema和formData。以上建议，谢谢。

**Comment by cipchk** [comment]
`sf` 包含 `getProperty` 可以获取属性对象，你可以对属性进行复杂操作，但是 `setVisible` 属于条件校验的一部分。
