### ISSUE TITLE
ERROR in node_modules/@delon/auth/src/token/jwt/jwt.guard.d.ts(12,5): error TS2416: Property 'canLoad' in type 'JWTGuard' is not assignable to the same property in base type 'CanLoad'

### ISSUE THREAD

**Issue by domsgit** [ng-alain/delon#360]
- ng-alain version: ^7.0.0-rc.2
- Angular version: ^6.1.10

## 【必填项】重现链接，Reproduction link

![image](https://user-images.githubusercontent.com/18412742/50581852-83c42b00-0e98-11e9-88f7-5b2be5f615d5.png)

## 重现步骤，Steps to reproduce
项目根目录下yarn start启动报错，发现是下图原因：
![image](https://user-images.githubusercontent.com/18412742/50581878-bbcb6e00-0e98-11e9-8a4a-6c5af9d28bf5.png)
改成下面以后报错就不会有了，就能启动了：
![image](https://user-images.githubusercontent.com/18412742/50581905-fdf4af80-0e98-11e9-8fb9-fecdfa65f28c.png)

**Comment by haoliangwu** [comment]
@domsgit angular-router@6.1.10 源码中的 canLoad 类型就是这个样子的，详见：[CanLoad](https://github.com/angular/angular/blob/c9488b543251980c96c7384f69042d958bde1bae/packages/router/src/interfaces.ts#L375)。

我觉的应该是这个库需要更新一下吧，虽然官方文档还是有 segments 参数的
![image](https://user-images.githubusercontent.com/6328186/50583410-f686d380-0ea3-11e9-8319-1cb8c7074b57.png)

**Comment by domsgit** [comment]
> @domsgit angular-router@6.1.10 源码中的 canLoad 类型就是这个样子的，详见：[CanLoad](https://github.com/angular/angular/blob/c9488b543251980c96c7384f69042d958bde1bae/packages/router/src/interfaces.ts#L375)。
> 
> 虽然官方文档是有 segments 参数的
> ![image](https://user-images.githubusercontent.com/6328186/50583410-f686d380-0ea3-11e9-8319-1cb8c7074b57.png)
> 
> 但这个是 7.0.x 以上版本的 router
> 
> 应该升级一下 @angular/router 的版本就好了

的确是这样子，我光升级了ng-alain到最新，没升级angular
