### ISSUE TITLE
reuseTab卡死

### ISSUE THREAD

**Issue by staneee** [ng-alain/delon#361]
- ng-alain version: 2.0.1
- Angular version: 6.1.10

## 【必填项】重现链接，Reproduction link
* 编译后文件: reuseTab.js
* 异常截图如下：
![image](https://user-images.githubusercontent.com/26987099/50622359-744feb00-0f47-11e9-9035-f1392142aac6.png)

**在这一行,ls的长度为0**
![image](https://user-images.githubusercontent.com/26987099/50622384-947faa00-0f47-11e9-960d-e67ede7ea705.png)

## 重现步骤，Steps to reproduce
* 从菜单导航跳转到A
* 从A页面按钮打开 B，B不复用，离开自动关闭
* 选中reuseTab中的B选项卡，击reuseTab菜单关闭A页面选项卡
* 在B页面通过router导航跳转到A页面，异常抛出

**此时reuseTab卡死**

**Comment by cipchk** [comment]
Pls upgrade to laster version and trying again.

**Comment by staneee** [comment]
delon组件库版本为2.0.1

**Comment by Anberm** [comment]
@cipchk 我知道这个，原因与 @staneee 描述的一致，
![image](https://user-images.githubusercontent.com/34148806/50732075-1d981a80-11ae-11e9-8886-05defad3eb40.png) combineLatest 的特性，让res是上次关闭的A路由，目前再次打开A路由，因为res还是关闭A时的notify，会使genList方法的isClosed为true，但是在路由复用策略里面，B是自动关闭的，所以在A路由的NavigationEnd时，genList的ls为空，就导致了ls.length<=1 为true，ls[0]就报错了，我这边以一个简单的方式处理这个事
![image](https://user-images.githubusercontent.com/34148806/50732136-54226500-11af-11e9-8fdc-d71e3ee12780.png)

**Comment by cipchk** [comment]
@Anberm 能否提供一个详细的重现步骤，根据 @staneee 步骤我无法在本地与测试用例中得到重现。

**Comment by Anberm** [comment]
@cipchk https://stackblitz.com/edit/angular-pbbjo1?file=src%2Fapp%2Fapp.module.ts
1.点击topage2
2.点击topage1
3.关闭page2
4.点击topage2
5.问题呈现

![reuse-tab](https://user-images.githubusercontent.com/34148806/50733866-68c32500-11d0-11e9-8ea3-c29cb488019a.gif)
