### ISSUE TITLE
图表组件不稳定，引起过多ng变更监测

### ISSUE THREAD

**Issue by anarckk** [ng-alain/delon#377]
🚨 Issues 是用于BUG、Feature、进度追踪 🚨
🚨 The issue tracker is not for questions 🚨

如果有任何问题，可在以下方式获得答案：

- https://ng-alain.com/
- QQ Group：316911865
- https://segmentfault.com/t/ng-alain

**Comment by anarckk** [comment]
https://github.com/ng-alain/delon/blob/e24ee4f699b4346c4b5884df9048f794d39f6c8c/packages/chart/pie/pie.component.ts#L129
建议用ngZone包起来

**Comment by anarckk** [comment]
建议这样修改为
https://github.com/ng-alain/delon/blob/e24ee4f699b4346c4b5884df9048f794d39f6c8c/packages/chart/pie/pie.component.ts#L203
![image](https://user-images.githubusercontent.com/27038948/50954068-560e6000-14f0-11e9-9785-da7f61f17f23.png)

使组件能稳定下来。而不会持续进行变更监测。

**Comment by cipchk** [comment]
请告知【不稳定】的定义是什么？另外能否提供一些更有价值的信息是否有必要这样子做？

**Comment by anarckk** [comment]
我指的不稳定，是持续不断的调用 ng view check 生命周期钩子（即使用户没有任何操作）。目前使用 g2-pie 组件会导致，一层一层的往上调用父级的 afterViewCheck 钩子，现在还不卡，可是我怕生产环境数据一多就卡。
我怀疑 this.install() 这个函数执行下去肯定有 setTimeout 或者 setInterval 。 所以建议，干脆在执行这个函数的时候使用 ngZone 。你觉得我理解的对吗

**Comment by cipchk** [comment]
所有 G2 都是 OnPush 模式，除非内部产生变更，否则不会因为外部的因素倒置额外不必要的触发变更检测。

> 建议：优化请务必在遇到性能问题时再开始考虑。

**Comment by anarckk** [comment]
OnPush 模式隔绝了外部对它的影响，但是不应该忽略它对外部的影响。

我认为，在用户长期没有任何操作，鼠标静止的条件下，组件的 afterViewCheck 钩子在触发几次之后，保持长期的静止是做为底层组件所应该做到的。

然而我在 g2-pie 组件写了 afterViewCheck 函数，打输出日志看到，g2-pie 组件会持续不断、永不停止地调用 afterViewCheck 并同时影响了上层的 afterViewCheck 钩子。这是个明显的不稳定组件。

所以，用 ngZone 避开变更监测，使组件稳定下来，我觉得是合理的建议。

**Comment by cipchk** [comment]
@anarckk 能否提供一个重现示例。

**Comment by anarckk** [comment]
我能提供一张截图
![image](https://user-images.githubusercontent.com/27038948/51093561-e514c400-17df-11e9-99fd-f24d4b67224f.png)
用的依赖是
![image](https://user-images.githubusercontent.com/27038948/51093601-4dfc3c00-17e0-11e9-8ff0-388066e2f895.png)
stackblitz 建的重现示例，运行不起来，我建个小工程，传个 zip 上来如何？
