### ISSUE TITLE
STComponent分页设置page.show未设置，ps>total时分页也显示出来了

### ISSUE THREAD

**Issue by visionding** [ng-alain/delon#380]
- ng-alain version: 7.0.0-rc.4
- Angular version: 7.2.0

delon.module中STComponent分页配置：
`    page: {
      placement: 'center',
      showQuickJumper: true,
    }
`
根据文档中的描述应当不会显示的

> page.show 是否显示分页器；当未指定时若 ps>total 情况下自动不显示

之前的版本没有这个问题

**Comment by cipchk** [comment]
该死，估计是 #378 引起的

**Comment by visionding** [comment]
加了show: undefined解决了，感谢
