### ISSUE TITLE
Unclear purpose of 'style-icons-auto.ts' and 'style-icons.ts'

### ISSUE THREAD

**Issue by uded** [ng-alain/delon#406]
Let me start with this - I translated the [documentation](https://github.com/ng-alain/delon/blob/7ef0c850300545c16b0860bbe9dc5f9ee6a2f22d/packages/theme/docs/icon.md) to my best abilities. I can only assume that the `auto` file should be somehow automagically generated by a build script, but I was unable to find any reference script for that. 

Is there an outline (requirement) or documentation to explain the purpose/mechanics better?

**Comment by uded** [comment]
I am aware of the change made in Antd, I am aware of the method to minimize static imports. What I am missing is how to generate/update that file automatically. If I need to run `ng g ng-alain:plugin icon` after each significant code change, which will introduce new icons or remove some - fine, I am all OK with that. But right now, after running scaffolding nothing has changed and I need to make all of the changes manually. It is not a bug, it's a confusing (or lacking) documentation that caused a challenge for me to understand what is going on here...

**Comment by uded** [comment]
OK, as I have tested it calling the plugin works well enough. My suggestion would be to change the scaffolding to add this as an `update-icons` script in `package.json` and document it accordingly, so anyone can include this in their build. 

Alternatively `style-icons-auto.ts` can be excluded from GIT and built with the default `build` command, as currently there is already a call to `color-less` script. That should be sufficient for the majority of users to avoid a problem as well but will require documentation regardless of possible automation.

**Comment by cipchk** [comment]
Close the delon issue and we will track bugs or features in the [ng-alain](https://github.com/ng-alain/ng-alain/issues) repository.
