### ISSUE TITLE
可否为ng g ng-alain:tpl 命令行工具增加选项以便在自定义模板中生成sf的schema或为st生成columns定义

### ISSUE THREAD

**Issue by personball** [ng-alain/delon#409]
---
背景介绍，我在做什么
---
嗨，我正在适配ng-alain单页前端到ABP模板项目。

ABP框架官网：[aspnetboilerplate.com](https://aspnetboilerplate.com/)   
Github：[Github.com/aspnetboilerplate](https://github.com/aspnetboilerplate/aspnetboilerplate)  
ABP项目启动模板：[module-zero-core-template](https://github.com/aspnetboilerplate/module-zero-core-template)

我的Repo：https://github.com/personball/abplus-zero-template
---
遇到的场景
---
Abp项目中后端集成了swagger在线接口文档，并使用了nswag工具来根据项目WebApi的在线swagger.json定义自动生成调用接口的typescript 服务代理类。

[nswag tool in template](https://github.com/personball/abplus-zero-template/tree/master/angular-ngalain/nswag)  

[@shared/service-proxies](https://github.com/personball/abplus-zero-template/tree/master/angular-ngalain/src/app/shared/service-proxies)

在自定义业务组件list/edit/view模板时，我想将上述类型定义利用起来，以自动生成`sf`的`schema`或者`st`的`columns`。

是否可以**为ng g ng-alain:tpl 命令行工具增加选项**以便在自定义模板中生成sf的`schema`定义或为st生成`columns`定义，例如

``` bash
ng g ng-alain:tpl list -m=setting --import-type=UserDto --import-path=@shared/service-proxies/service-proxies.ts

// or
ng g ng-alain:tpl list -m=setting --import-type=UserDto --import-swagger=./nswag/swagger.json

```
swagger.json 结构示例
```javascript
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "AbpProjectName API"
  },
  "paths": {
   // ...
   },
   "definitions": {
   // ...
      "UserDto": {
      "required": ["userName", "name", "surname", "emailAddress"],
      "type": "object",
      "properties": {
        "userName": {
          "maxLength": 256,
          "minLength": 0,
          "type": "string"
        },
        "name": {
          "maxLength": 64,
          "minLength": 0,
          "type": "string"
        },
        "surname": {
          "maxLength": 64,
          "minLength": 0,
          "type": "string"
        },
        "emailAddress": {
          "maxLength": 256,
          "minLength": 0,
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "fullName": {
          "type": "string"
        },
        "lastLoginTime": {
          "format": "date-time",
          "type": "string"
        },
        "creationTime": {
          "format": "date-time",
          "type": "string"
        },
        "roleNames": {
          "uniqueItems": false,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "id": {
          "format": "int64",
          "type": "integer"
        }
      }
    },
   // ...
   }
}
```

**Comment by cipchk** [comment]
在不考虑如何解析的情况下，我觉得可以增加一种修复的能力，例如执行命令行

```bash
ng g ng-alain:tpl list -m=setting --import-type=UserDto --import-swagger=./nswag/swagger.json
```

运行前，允许调用相应的自定义运行 JS 脚本，例如 `_cli-tpl/_fix.js`，一个简单的样本：

```js
function fix(options) {
  return Promise.resolve(val);
}

module.exports = {
  fix
};
```

固定一个方法名 `fix` 作为入口，`options` 参数包含所有 CLI 对应的参数，包括 `--import-type` 等问题，一个参数接口示例：

```js
{
  "tplName": "test",
  "modal": true,
  "extraArgs": {
    "import-type": "UserDto"
  }
}
```

`options` 参数会被应用到模板引擎当中，因此当在 `_fix.js` 对 `options` 的修改会响应到模板引擎当中，例如增加 `AA: 'asdf'` 参数，则对应的 `__name@dasherize__.component.html` 可以增加以下占位符：

```html
<page-header></page-header>
<%= AA %>
```

结果为：

```html
<page-header></page-header>
asdf
```

> 其他模板文件等同

`fix` 函数必须是 Promise 这样给修复提供更多空间。

> **注：** CLI 是一个 Node JS 程序，因此语法以 Node JS 为准。

**Comment by personball** [comment]
@cipchk 我可以这样理解么：
    通过fix(options)，我可以在模板渲染前构造sf的schema或者st的columns，然后直接塞到options里，然后在模板里可以直接输出schema或者columns变量？

**Comment by personball** [comment]
把解析的逻辑实现留给想要自定义模板的人，明白了，类似于加一个hook。
