### ISSUE TITLE
formPath is diff with the path in sf.getValue('path')

### ISSUE THREAD

**Issue by lovedemo** [ng-alain/delon#418]
## 【必填项】重现链接，Reproduction link: https://ng-alain-setup-fqvx2y.stackblitz.io/

代码：https://stackblitz.com/edit/ng-alain-setup-fqvx2y

## 重现步骤，Steps to reproduce

1.添加三个表单，a随机选，b 随机输入
2.删除第二表单
3.在当前第二个表单输入b的值

## 原因 两边的path策略不同，在验证表单时不能取到当前表单对应的值

**Comment by cipchk** [comment]
`ArrayProperty` 是一个全局自增TICK，因此你不应该拿最后一个ID来作为其校验路径，其实一种更合理的办法是通过 `formP.parent.properties` 来获取当前项的所有属性集合。
