### ISSUE TITLE
schema建议

### ISSUE THREAD

**Issue by jerrytang67** [ng-alain/delon#424]
正在做一个.net core的class to SfSchema的库
参考了gitlab现有的几个jsonSchema库
properties中type基本都支持像这样 "type": [ "string", "null" ]
表示Db中一个nullable的字段

**Comment by cipchk** [comment]
sf 不会考虑非标准行为，[type](https://json-schema.org/understanding-json-schema/reference/type.html) 规则中并不支持数组类型。

**Comment by jerrytang67** [comment]
In the following example, we accept strings and numbers, but not structured data types:

{ "type": ["number", "string"] }
42
"Life, the universe, and everything"
["Life", "the universe", "and everything"]
For each of these types, there are keywords that only apply to those types. For example, numeric types have a way of specifying a numeric range, that would not be applicable to other types. In this reference, these validation keywords are described along with each of their corresponding types in the following chapters.
