### ISSUE TITLE
Hard-coded text in DateRangePickerConfig

### ISSUE THREAD

**Issue by TheAifam5** [ng-alain/delon#477]
Hey!

I noticed that the text for ahortcuts are hardcoded in the configuration.

Could you use i18n or remove it completely?

Regards,
TheAifam5

**Comment by cipchk** [comment]
![image](https://user-images.githubusercontent.com/2987467/54681018-ed6de000-4b3d-11e9-895d-b715a70ca4f4.png)

> Deron issues have been closed, please use https://github.com/ng-alain/ng-alain/issues
