### ISSUE TITLE
[Bug] STColumn - format first parameter is invalid

### ISSUE THREAD

**Issue by TheAifam5** [ng-alain/delon#488]
Hey,

I noticed that in STColumn you have a property named „format” which has two arguments (STData, STColumn).

The first argument is not a STData in the STColumn case but a raw data for the row. 

The secod parameter is a column properties of type STColumn.

Looks like the documentation is outdated.

Regards,
TheAifam5

**Comment by cipchk** [comment]
Deron issues have been closed, please use ng-alain/ng-alain/issues
