### ISSUE TITLE
[Request] Rename „theme” package to „core” or split them.

### ISSUE THREAD

**Issue by TheAifam5** [ng-alain/delon#490]
Hey,
The current package of the name „theme” has multiple tasks like design configuration, services, pipes and LESS/themes files.

Would not be better to split the package or rename it?

So that the core package would have:
- pipes
- services

For „@delon/theme” rest stuff like LESS files, layouts etc...

For translations I would create a separated package to have all translations there like „@delon/i18n” and use it in other packages/components.

Regards,
TheAifam5

**Comment by cipchk** [comment]
Deron issues have been closed, please use ng-alain/ng-alain/issues
