### ISSUE TITLE
page-header的autoTitle属性不起作用

### ISSUE THREAD

**Issue by tangjwt** [ng-alain/delon#515]
使用以下方式调用page-header，
<page-header [autoTitle]="false"></page-header>
预期不生成单独的标题，实际仍会生成标题。

使用版本：7.0.2，升级到7.1.0版本 也有同样的问题。

**Comment by cipchk** [comment]
Deron issues have been closed, please use ng-alain/ng-alain/issues

**Comment by cipchk** [comment]
`autoTitle` 是指会利用 Menu 或 路由数据自动根据URL自动定位，其他细节请至 https://github.com/ng-alain/ng-alain 提供一个有效的重现示例。
