### ISSUE TITLE
升级7.6.1版本后 导致分页不显示(有重现demo(见附件))

### ISSUE THREAD

**Issue by spt110** [ng-alain/delon#606]
重现分页控件不显示的demo例子(见附件)
[下载附件ng-web.zip](https://github.com/ng-alain/delon/files/3285372/ng-web.zip)
npm start
打开http://localhost:4200/#/system/users
![image](https://user-images.githubusercontent.com/5217855/59424332-5e9ff500-8e06-11e9-81d9-78f1bba4123b.png)
![image](https://user-images.githubusercontent.com/5217855/59425044-bbe87600-8e07-11e9-953d-80539e93170a.png)

**Comment by spt110** [comment]
重现的demo例子(见附件)
[ng-web.zip](https://github.com/ng-alain/delon/files/3285372/ng-web.zip)
npm start
打开http://localhost:4200/#/system/users
![image](https://user-images.githubusercontent.com/5217855/59424332-5e9ff500-8e06-11e9-81d9-78f1bba4123b.png)

**Comment by cipchk** [comment]
Deron issues have been closed, please use https://github.com/ng-alain/ng-alain/issues
